[package]
name = "l07-error-handling"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
derive_more = "0.99.17"
serde = { version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"