### V1: GET profile
GET http://localhost:8080/v1/profile

### V1: POST profile
POST http://localhost:8080/v1/profile

### V2: GET profile
GET http://localhost:8080/v2/profile

### V2: POST profile
POST http://localhost:8080/v2/profile
